# Copyright 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 1
    groups:
      ga-actions-dependencies:
        applies-to: version-updates
        patterns:
        - ".github/workflows/*"
    ignore:
      - dependency-name: ".github/workflows/*"
        update-types: ["version-update:semver-patch"] # Ignore patch updates