# Copyright 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Scan Python code with Bandit

on:
    workflow_dispatch:
    push:
    pull_request:
      paths:
        - '**/*.py'
        - '.github/workflows/bandit.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bandit:
    name: Bandit
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Clone the git repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit and output results
        run: |
          mkdir -p bandit_reports
          bandit -c .github/workflows/bandit.config -r . -f txt -o bandit_reports/bandit_output.txt
          bandit -c .github/workflows/bandit.config -r . -f sarif -o bandit_reports/bandit_output.sarif

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@2d790406f505036ef40ecba973cc774a50395aac # v3.25.13
        with:
          sarif_file: bandit_reports/bandit_output.sarif

      - name: Upload Bandit text report as artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: bandit-report
          path: bandit_reports/bandit_output.txt