# Copyright 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Coverity
# It runs static analysis build - Coverity. It requires special token (set in CI's secret).

permissions:
  contents: read-all

on:
  workflow_dispatch:
  schedule:
    # Run every day at 22:00 UTC
    - cron: '0 22 * * *'

env:
  COVERITY_SCAN_NOTIFICATION_EMAIL:  ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
  COVERITY_SCAN_TOKEN:               ${{ secrets.COVERITY_SCAN_TOKEN }}
  COVERITY_SCAN_PROJECT_NAME:        ${{ secrets.COVERITY_SCAN_PROJECT_NAME }}
  COVERITY_SCAN_BUILD_COMMAND:       "cmake --build ${{github.workspace}}/build"
  COVERITY_SCAN_BRANCH_PATTERN:      "main"

jobs:
  linux:
    name: Coverity
    runs-on: ubuntu-22.04
    env:
      LLVM_VERSION: "17.0"
      LLVM_TAR: llvm-17.0.6-ubuntu18.04-Release+Asserts-x86.arm.wasm.tar.xz

    steps:
      - name: Clone the git repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install dependencies
        run: |
         .github/workflows/scripts/install-build-deps.sh

      - name: Check environment
        run: |
          which -a clang
          cat /proc/cpuinfo

      - name: Build package
        run: |
          .github/workflows/scripts/build-ispc.sh

      - name: Run Coverity
        run: |
          .github/workflows/scripts/run-coverity.sh