# Copyright 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Check against DLL injection (trunc)

permissions: read-all

on:
  workflow_dispatch:
  schedule:
    # Run every day at 22:00 UTC
    - cron: '0 22 * * *'

env:
  ZIP_URL: https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-windows.zip?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202019%2C%20LLVM_VERSION%3Dlatest

jobs:
  scan:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install procmon and wget
      run: |
        Install-ChocoPackage wget
        Install-ChocoPackage procmon
        Install-ChocoPackage 7zip
        pip install defusedxml
      shell: powershell

    - name: Download ISPC Release Archives
      run: |
        echo "Download artifact $ZIP_URL" >> "%GITHUB_STEP_SUMMARY%"
        wget --quiet -O archive.zip "$ZIP_URL"
        7z x "$ZIP"
        ls -al
        cd ispc-*
        ISPC_BIN_DIR="ispc-trunk-windows/bin"
        echo "$ISPC_BIN_DIR" >> "$GITHUB_PATH"
      shell: bash

    - name: Check ISPC binary for DLL injection
      run: |
        python .github\workflows\scripts\check-dll-injection.py dbghelp.dll
      shell: cmd

    - name: Upload results
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      if: always()
      with:
        name: reports
        path: |
          dll_load_filtered.xml
