name: (INTERNAL) Check copyright

on: [pull_request]

jobs:
  check_copyright:
    runs-on: [Linux, docker]
    container:
      image: amr-registry.caas.intel.com/ispc/ubuntu:22.04

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
        submodules: false

    - name: Check copyright
      run: |
        ./scripts/check_copyright.sh "origin/$GITHUB_BASE_REF"

